sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  hosts:
      - magento2.travis
language: php
php:
 - 7.0
 - 7.1

env:
  matrix:
    - MAGENTO_VERSION=2.2.4
    - MAGENTO_VERSION=2.1.*

matrix:
  exclude:
    - php: 7.0
      env: MAGENTO_VERSION=2.2.4
    - php: 7.1
      env: MAGENTO_VERSION=2.1.*

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

install: sh ./Test/install.sh
script:
  - /tmp/magento2/vendor/bin/phpunit -c /tmp/magento2/dev/tests/integration/phpunit.xml.dist /tmp/magento2/app/code/Davay/CarrierTemplates
